apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft.fullname" . }}-secrets
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
stringData:
  RCON_PASSWORD: {{ include "minecraft.rconPassword" .Values.server.config }}
