apiVersion: v2
name: minecraft
description: A Minecraft Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.18.0"
sources:
  - https://github.com/zoomoid/iron-helm
maintainers:
  - name: Alexander Bartolomey
    email: occloxium@gmail.com